PageFactory architecture and ui tests
Nadya101/QaseDiploma pull request #1
Opened 2022-01-02 13:47 UTC by Nadya101

2022-01-02 14:50 UTC, vchesnakoutest requested changes

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/constants/IConstants.java
> +
пустые строки удаляй

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/BasePage.java
> +    }
их лучше в отдельный класс. utils/Waiters.java

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/DeleteProjectPage.java
> +        confirmDeleteButton.click();
отступ подправь

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/LoginPage.java
> +    public boolean hasAttributeRequiredAndErrorMessageAppears(){
давай лучше проверять, что урл равен https://app.qase.io/login

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewProjectPage.java
> +    public String createRandomProjectCode() {
generateRandomProjectCode

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewProjectPage.java
> +    public NewProjectPage makePublicProject(boolean isPublicProject) {
makePublicOrPrivateProject

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewProjectPage.java
> +            System.out.println("select public");
System.out.println - не должно быть в проекте. Их надо будет заменить на логгер. Можно сделать потом, только не забудь

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewTestCasePage.java
> +    @FindBy(xpath = "//p[@data-placeholder='For example: We can authorize on page http://example.com/login']")
тут лучше contains использовать и брать только часть текста: 'We can authorize on page' например

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewTestCasePage.java
> +    private WebElement behaviorDropDown;
такие локаторы не надежны. в данном случае лучше привязываться к тексту

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewTestCasePage.java
> +    private WebElement postConditionInput;
используй contains, "wysiwyg" - выглядит не надежно

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewTestCasePage.java
> +
убери два лишних пробела

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewTestCasePage.java
> +    public NewTestCasePage isFlaky(String flaky) {
setIsFlaky

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/NewTestCasePage.java
> +
удаляй лишние пробелы в конце

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +    @FindBy(xpath = "//*[@class = 'style_item-2O69D style_delete-3r6xI']")
-3r6xI - выглядит не надежно

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        Actions action = new Actions(driver);
для actions > moveToElement создай отдельный метод в utils/Actions

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        WebElement caseLine = driver.findElement(By.xpath("//*[contains(text(), 'Case101')]"));
Case101 - эти данные должны приходить из тестов

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        WebElement suiteMenu = driver.findElement(By.xpath("//*[@title='"+ suiteName +"']/ancestor::*[@class='common_draggable-2vPcC']//*[@class='fa fa-ellipsis-h']"));
-2vPcC и fa fa-ellipsis-h выглядит не надежно

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +
много пробелов

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +        deleteMenu.click();
можно сразу driver.findElement(menuDropDown).click();

2022-01-02 14:50 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +
1 лишний пробел

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/BaseTest.java
> +        deleteSuiteModal = new DeleteSuiteModal(driver);
давай инициализацию вынесем в отдельный метод и будем тут его вызывать

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/LoginTest.java
> +        Assert.assertTrue(loginPage.hasAttributeRequiredAndErrorMessageAppears());
тут будем проверять урл

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/SearchTest.java
> +
удали 1 лишний пробел

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/TestCaseTest.java
> +                .clickOnSaveButton();
нету ассерта

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/TestCaseTest.java
> +                .clickOnSaveButton();
нету ассерта

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/TestCaseTest.java
> +                .clickOnSaveButton();
1.тут надо будет сделать это в steps.
2.для всех этих данных лучше будет создать объект TestCase со всеми этими свойствами.

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/TestCaseTest.java
> +
лишний пробел

2022-01-02 14:50 UTC, vchesnakoutest commented on src/test/java/tests/ui/TestCaseTest.java
> +
добавить ассерт

2022-01-02 23:09 UTC, Nadya101 commented on src/main/java/ui/pages/NewProjectPage.java
> +            System.out.println("select public");
Уже потом сделаю логгер, а System.out.println  убрала

2022-01-09 19:38 UTC, vchesnakoutest requested changes

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/EditSuiteModal.java
> +    @Step("Add suite description")
в @Step добавь параметр text

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/DeleteTestCaseModal.java
> +
удаляй пустые строки

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        waitForElementLocated(driver, By.xpath(String.format("//*[contains(@class, 'style_caseTitle')][contains(text(),'%s')]", caseName)), 5);
"//*[contains(@class, 'style_caseTitle')][contains(text(),'%s')]" - давай выносить в константу

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        driver.findElement(By.xpath(String.format("//*[contains(@class, 'style_caseTitle')][contains(text(),'%s')]", caseName))).click();
тут надо будет исп. константу

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +                "'style_header')]//*[contains(@class, 'trash')]", suiteName))).click();
тоже для локаторов заводи константы

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        List<WebElement> suiteTitle = driver.findElements(By.xpath(String.format("//*[@title='" + suiteName + "']", suiteName)));
если используешь string format, то надо писать: By.xpath(String.format("//*[@title='%s']", suiteName)));

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectPage.java
> +        driver.findElement(By.xpath(String.format("//*[contains(text(), '%s')]/ancestor::*[contains(@class, 'style_header')]//*[contains(@class, 'pencil')]",
локаторы в константы (проверь также в остальных местах, там много где такое встречается)

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +        By menuDropDown = By.xpath(String.format("//*[contains(text(), '%s')]/ancestor::tr[@class='project-row']" +
исправить

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +        By projectTitle = By.xpath(String.format("//*[contains(text(), '%s')]", name));
исправить

2022-01-09 19:38 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +                "//*[contains(text(),'%s')]", name)), 5);
исправить

2022-01-14 20:26 UTC, Nadya101 commented on src/main/java/ui/pages/ProjectPage.java
> +        driver.findElement(By.xpath(String.format("//*[contains(text(), '%s')]/ancestor::*[contains(@class, 'style_header')]//*[contains(@class, 'pencil')]",
Везде исправила)

2022-01-14 20:35 UTC, Nadya101 commented on src/main/java/ui/pages/ProjectPage.java
> +        List<WebElement> suiteTitle = driver.findElements(By.xpath(String.format("//*[@title='" + suiteName + "']", suiteName)));
Исправила

2022-01-15 16:53 UTC, merged