APi tests added
Nadya101/QaseDiploma pull request #2
Opened 2022-01-09 19:43 UTC by Nadya101

2022-01-09 20:08 UTC, vchesnakoutest requested changes

2022-01-09 20:08 UTC, vchesnakoutest commented on src/main/java/api/adapters/BaseAdapter.java
> +    public final String token = "";
public final String TOKEN

2022-01-09 20:08 UTC, vchesnakoutest commented on src/main/java/api/adapters/BaseAdapter.java
> +    public final String SPECIFIC_TEST_CASE = "/case/%s/%d";
эти константы должны лежать в адаптерах, где они используются

2022-01-09 20:08 UTC, vchesnakoutest commented on src/main/java/api/adapters/BaseAdapter.java
> +    }
зачем эта конструкция?

2022-01-09 20:08 UTC, vchesnakoutest commented on src/main/java/api/adapters/BaseAdapter.java
> +    Property property;
зачем это?

2022-01-09 20:08 UTC, vchesnakoutest commented on src/main/java/api/adapters/BaseAdapter.java
> +                        .header("Content-Type", contentType)
строки "Token","Content-Type" и тд тоже выноси в константы

2022-01-09 20:08 UTC, vchesnakoutest commented on src/test/java/tests/api/TestCaseApiTest.java
> +        Assert.assertEquals(response.getStatusCode(), 200);
в апишке желательно проверять не только статус коды, но и тело респонса. Пока можно оставить так, но потом надо будет дополнить если время останется.

2022-01-09 20:08 UTC, vchesnakoutest commented on src/test/java/tests/api/TestCaseApiTest.java
> +        Response response = new TestCaseAdapter().getTestById("FP9548", 35);
давай в этом тесте мы будет создавать тест с нуля и потом айди этого теста передавать в getTestById

2022-01-09 20:08 UTC, vchesnakoutest commented on src/test/java/tests/api/TestSuiteApiTest.java
> +        Response response = new TestSuiteAdapter().getSuiteById("COMEMAI", 1);
тут тоже давай создавать сьют с нуля и передавать его в getSuiteById

2022-01-14 19:03 UTC, Nadya101 commented on src/main/java/api/adapters/BaseAdapter.java
> +    }
Удалила с проекта, проперти будут в Jenkins

2022-01-14 19:09 UTC, Nadya101 commented on src/main/java/api/adapters/BaseAdapter.java
> +    Property property;
удалила

2022-01-15 15:16 UTC, vchesnakoutest approved these changes

2022-01-15 16:53 UTC, merged