Join API and UI tests
Nadya101/QaseDiploma pull request #4
Opened 2022-01-20 18:16 UTC by Nadya101

2022-01-21 13:20 UTC, vchesnakoutest requested changes

2022-01-21 13:20 UTC, vchesnakoutest commented on src/main/java/api/adapters/BaseAdapter.java
> +    @Step("Delete object by id = '{id}' and send Delete request to URL: '{url}'")
{id} - тут нигде не передается.

Лучше напиши просто:
Send 'Delete' request to URL: '{url}'

2022-01-21 13:20 UTC, vchesnakoutest commented on src/main/java/api/adapters/ProjectAdapter.java
> +
удали пустую строку

2022-01-21 13:20 UTC, vchesnakoutest commented on src/main/java/api/models/Project.java
> +String group;
добавь отступы

2022-01-21 13:20 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +    public final String COMEMAI_PROJECT_XPATH = "//*[contains(text(), 'ComeMai')]/ancestor::tr[@class='project-row']//*[@class ='fa fa-ellipsis-h']";
'ComeMai' - это хардкод данных проекта. Тебе нужно имя проекта передавать сюда через параметр из теста.
COMEMAI_PROJECT_XPATH > PROJECT_XPATH

2022-01-21 13:20 UTC, vchesnakoutest commented on src/main/java/ui/pages/ProjectsPage.java
> +        boolean isPresent = !(targetProject.size() <= 0);
targetProject.size() не может быть меньше нуля.

лучше написать:
boolean isPresent = targetProject.size() > 0;

2022-01-21 13:20 UTC, vchesnakoutest commented on src/test/java/tests/ui/BaseTest.java
> +    String password = "gQGdpPJ3AFZ*85Z";
потом не забудь это считывать через PropertyReader

2022-01-22 18:58 UTC, Nadya101 commented on src/main/java/ui/pages/ProjectsPage.java
> +    public final String COMEMAI_PROJECT_XPATH = "//*[contains(text(), 'ComeMai')]/ancestor::tr[@class='project-row']//*[@class ='fa fa-ellipsis-h']";
Замінила щоб шукав button:        waitForElementLocated(driver, addFilterButton, 5);

2022-01-22 18:59 UTC, merged